export { default as SplashScreen } from './SplashScreen';
export { Onboarding, Terms, Langugage } from './Auth';
export {
  Welcome,
  SmartWays,
  HelpAndFeedback,
  ContactUs,
  AboutUs,
  Details,
  EMI,
  LoanEligibility,
  CompareLoans,
  TaxCalculation,
  EquityLinkedScheme,
  Lumpsum,
  SIP,
  SWP,
  Theory,
  FAQ,
  FixedDeposit,
  RecurringDeposit,
  PublicProvidentFund,
  SimpleAndCompound,
  CurrencyConversion,
  DiscountCalculator,
  PriceCalculator,
  MarginCalculator,
  MarkupCalculator,
  OperatingMargin,
  MarginWithSales,
} from './App';
